version: '2'
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "7070:7070"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      # Inject your specific service account keyfile into the container at runtime.
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro