services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kredoh-paybill
    ports:
      - "7070:7070"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /opt/.google/google.json      # Silence gRPC ALTS warnings
      GRPC_VERBOSITY: ERROR
      GRPC_ENABLE_FORK_SUPPORT: "0"
    volumes:
      - /opt/.google/google.json:/opt/.google/google.json:ro
      # Persistent data volume
      - app_data:/opt/kredoh-paybill/data
    networks:
      - mynet
    restart: unless-stopped

networks:
  mynet:
    driver: bridge

volumes:
  app_data:
    driver: local