version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/keyfile.json
    volumes:
      # Inject your specific service account keyfile into the container at runtime.
      - ${GCP_KEY_PATH}:/opt/.google/google.json:ro